### ISSUE TITLE
Sequencer ignores config and updates master shard

### ISSUE THREAD

**Issue by taka-oyama** [drecom/activerecord-turntable#25]
Haven't figured out the whole thing yet but the config for sequencer is completely ignored.

The code below is where it gets ignored.

`lib/active_record/turntable/cluster.rb:16`
```ruby
# setup sequencer
if (seq = (@options[:seq] || @config[:seq])) && seq[:type] == :mysql
  @seq_shard = SeqShard.new(seq)
end
```

There is no `:type` inside `seq`, there is only a sequence name like `user_seq`.
I tried doing something like `@seq_shard = SeqShard.new(seq["user_seq"])` but that raised an error below.

`/usr/lib64/ruby/gems/2.2.0/gems/activerecord-turntable-2.1.1/lib/active_record/turntable/shard.rb:43:in create_connection_class': undefined method with_indifferent_access' for nil:NilClass (NoMethodError)`

Thoughts?

**Comment by gussan** [comment]
Thank you for reporting.
`Sequencer::Mysql` seems to be broken, I'll fix this.

**Comment by taka-oyama** [comment]
:smiley:
