### ISSUE TITLE
undefined local variable doing rake db:migrate

### ISSUE THREAD

**Issue by max605b** [drecom/activerecord-turntable#30]
Using Rails 4 and Turntable gem 2.1.1 (and 2.2.0), doing a rake db:migrate leads to the following error:

NameError: undefined local variable or method `config' for main:Object
~/.rvm/gems/ruby-2.1.5/gems/activerecord-turntable-2.1.1/lib/active_record/turntable/railties/databases.rake:81:in `block (4 levels) in <top (required)>'

After performing migrations, it calls dump, which has this line:
        shard_configs.merge!(config["seq"]) if config["seq"]

The variable 'config' is not set.  'current_config' is set.  In other methods in the file, 'config' is initialized as:
        config = ActiveRecord::Base.configurations[Rails.env]

Should config be set or should it be using current_config or do I not have something configured properly in turntable.yml or database.yml?

**Comment by gussan** [comment]
Thx, I'll fix it soon.
